spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/edurite_test
    username: postgres
    password: Crt@Ailsa

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration

  cache:
    type: none

  data:
    redis:
      repositories:
        enabled: false

security:
  jwt:
    secret: edurite-secure-jwt-secret-key-2026-ultra-secure-token-authentication-key