spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/edurite}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:}

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      repositories:
        enabled: false

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED}
    locations: ${SPRING_FLYWAY_LOCATIONS}

server:
  port: ${SERVER_PORT:8080}

security:
  jwt:
    secret: ${JWT_SECRET:}
    access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
    refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

gemini:
  api-key: ${GEMINI_API_KEY}
  model: ${GEMINI_MODEL}
  base-url: ${GEMINI_BASE_URL}