spring:
  application:
    name: edurite-backend

  profiles:
    active: dev

  data:
    redis:
      repositories:
        enabled: false

  cache:
    type: redis

security:
  jwt:
    secret: edurite-super-secure-jwt-secret-key-2026-ultra-secure-authentication-token-system-key
    access-token-expiration: 3600
    refresh-token-expiration: 604800

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html