spring:
  application:
    name: edurite-backend
  profiles:
    active: dev

  data:
    redis:
      repositories:
        enabled: false

  cache:
    type: redis

security:
  jwt:
    secret: change-me-with-a-very-long-random-64-byte-secret-change-me-with-a-very-long-random-64-byte-secret
    access-token-expiration: 3600
    refresh-token-expiration: 604800

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html